#!/bin/bash

if [ -z "$1" ]; then
  echo "Debe especificar un mensaje!"
else
  echo "Pusheando..."
  rm -rf tmp
  git add -A
  git commit -am "$1"
  git push xaver master

  bundle exec cap production deploy
fi
