development:
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  database: coala
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  username: # username
  password: # password
  database: coala-production
  host: localhost
