# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d5693980c66f802931177ee17ffc7b766c8c60eae5657f05cc18d77722982af143bed3277cd2f722f521b5e06597076d90ab0450ef7c7f557fd7b463455bf11

test:
  secret_key_base: 8c51b82b649a07051aa46c3608797a740aa7c55b7bec3ee582ee26ddfb6e9423ed870b635d5757450c972dc12c977f9d0df32a86ed853442dcd65be741fd42b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 0d5693980c66f802931177ee17ffc7b766c8c60eae5657f05cc18d77722982af143bed3277cd2f722f521b5e06597076d90ab0450ef7c7f557fd7b463455bf11
